"""Static metadata registry for all tunable settings.

Each entry maps a Settings attribute name to display metadata,
category, type constraints, risk level, and DI caches that must be
cleared on change.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from app.settings_registry.schemas import SettingCategory, SettingRiskLevel, SettingType


@dataclass(frozen=True, slots=True)
class SettingMeta:
    display_name: str
    description: str
    category: SettingCategory
    setting_type: SettingType
    risk_level: SettingRiskLevel
    min_value: float | None = None
    max_value: float | None = None
    unit: str | None = None
    step: float | None = None
    di_caches: list[str] = field(default_factory=list)
    requires_flag: str | None = None


SETTING_REGISTRY: dict[str, SettingMeta] = {
    # --- Retrieval & Embedding ---
    "retrieval_text_limit": SettingMeta(
        display_name="Text Retrieval Limit",
        description="Maximum number of text chunks retrieved per query.",
        category=SettingCategory.RETRIEVAL,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=1,
        max_value=100,
        unit="chunks",
    ),
    "retrieval_graph_limit": SettingMeta(
        display_name="Graph Retrieval Limit",
        description="Maximum number of graph nodes retrieved per query.",
        category=SettingCategory.RETRIEVAL,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=1,
        max_value=50,
        unit="nodes",
    ),
    "retrieval_prefetch_multiplier": SettingMeta(
        display_name="Prefetch Multiplier",
        description="Multiplier applied to retrieval limit for candidate prefetch.",
        category=SettingCategory.RETRIEVAL,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=1,
        max_value=10,
    ),
    "retrieval_dense_prefetch_multiplier": SettingMeta(
        display_name="Dense Prefetch Multiplier",
        description="Multiplier for dense vector prefetch in RRF fusion.",
        category=SettingCategory.RETRIEVAL,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=1,
        max_value=10,
    ),
    "retrieval_sparse_prefetch_multiplier": SettingMeta(
        display_name="Sparse Prefetch Multiplier",
        description="Multiplier for sparse vector prefetch in RRF fusion.",
        category=SettingCategory.RETRIEVAL,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=1,
        max_value=10,
        requires_flag="enable_sparse_embeddings",
    ),
    "query_entity_threshold": SettingMeta(
        display_name="Entity Filter Threshold",
        description="Confidence threshold for entity-based retrieval filtering.",
        category=SettingCategory.RETRIEVAL,
        setting_type=SettingType.FLOAT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=0.0,
        max_value=1.0,
        step=0.05,
    ),
    "reranker_top_n": SettingMeta(
        display_name="Reranker Top-N",
        description="Number of chunks kept after cross-encoder reranking.",
        category=SettingCategory.RETRIEVAL,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.CACHE_CLEAR,
        min_value=1,
        max_value=50,
        unit="chunks",
        di_caches=["get_reranker", "get_retriever"],
        requires_flag="enable_reranker",
    ),
    "matryoshka_search_dimensions": SettingMeta(
        display_name="Matryoshka Search Dimensions",
        description="Truncated vector dimensions for search (0 = disabled).",
        category=SettingCategory.RETRIEVAL,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.RESTART,
        min_value=0,
        max_value=2048,
        unit="dims",
    ),
    # --- Adaptive Retrieval Depth ---
    "retrieval_depth_factual_text": SettingMeta(
        display_name="Factual — Text Depth",
        description="Text chunks retrieved for factual queries.",
        category=SettingCategory.ADAPTIVE_DEPTH,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=5,
        max_value=100,
        unit="chunks",
        requires_flag="enable_adaptive_retrieval_depth",
    ),
    "retrieval_depth_factual_graph": SettingMeta(
        display_name="Factual — Graph Depth",
        description="Graph nodes retrieved for factual queries.",
        category=SettingCategory.ADAPTIVE_DEPTH,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=2,
        max_value=50,
        unit="nodes",
        requires_flag="enable_adaptive_retrieval_depth",
    ),
    "retrieval_depth_analytical_text": SettingMeta(
        display_name="Analytical — Text Depth",
        description="Text chunks retrieved for analytical queries.",
        category=SettingCategory.ADAPTIVE_DEPTH,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=5,
        max_value=100,
        unit="chunks",
        requires_flag="enable_adaptive_retrieval_depth",
    ),
    "retrieval_depth_analytical_graph": SettingMeta(
        display_name="Analytical — Graph Depth",
        description="Graph nodes retrieved for analytical queries.",
        category=SettingCategory.ADAPTIVE_DEPTH,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=2,
        max_value=50,
        unit="nodes",
        requires_flag="enable_adaptive_retrieval_depth",
    ),
    "retrieval_depth_comparative_text": SettingMeta(
        display_name="Comparative — Text Depth",
        description="Text chunks retrieved for comparative queries.",
        category=SettingCategory.ADAPTIVE_DEPTH,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=5,
        max_value=100,
        unit="chunks",
        requires_flag="enable_adaptive_retrieval_depth",
    ),
    "retrieval_depth_comparative_graph": SettingMeta(
        display_name="Comparative — Graph Depth",
        description="Graph nodes retrieved for comparative queries.",
        category=SettingCategory.ADAPTIVE_DEPTH,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=2,
        max_value=50,
        unit="nodes",
        requires_flag="enable_adaptive_retrieval_depth",
    ),
    "retrieval_depth_timeline_text": SettingMeta(
        display_name="Timeline — Text Depth",
        description="Text chunks retrieved for timeline queries.",
        category=SettingCategory.ADAPTIVE_DEPTH,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=5,
        max_value=100,
        unit="chunks",
        requires_flag="enable_adaptive_retrieval_depth",
    ),
    "retrieval_depth_timeline_graph": SettingMeta(
        display_name="Timeline — Graph Depth",
        description="Graph nodes retrieved for timeline queries.",
        category=SettingCategory.ADAPTIVE_DEPTH,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=2,
        max_value=50,
        unit="nodes",
        requires_flag="enable_adaptive_retrieval_depth",
    ),
    "retrieval_depth_procedural_text": SettingMeta(
        display_name="Procedural — Text Depth",
        description="Text chunks retrieved for procedural queries.",
        category=SettingCategory.ADAPTIVE_DEPTH,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=5,
        max_value=100,
        unit="chunks",
        requires_flag="enable_adaptive_retrieval_depth",
    ),
    "retrieval_depth_procedural_graph": SettingMeta(
        display_name="Procedural — Graph Depth",
        description="Graph nodes retrieved for procedural queries.",
        category=SettingCategory.ADAPTIVE_DEPTH,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=2,
        max_value=50,
        unit="nodes",
        requires_flag="enable_adaptive_retrieval_depth",
    ),
    "retrieval_depth_exploratory_text": SettingMeta(
        display_name="Exploratory — Text Depth",
        description="Text chunks retrieved for exploratory queries.",
        category=SettingCategory.ADAPTIVE_DEPTH,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=5,
        max_value=100,
        unit="chunks",
        requires_flag="enable_adaptive_retrieval_depth",
    ),
    "retrieval_depth_exploratory_graph": SettingMeta(
        display_name="Exploratory — Graph Depth",
        description="Graph nodes retrieved for exploratory queries.",
        category=SettingCategory.ADAPTIVE_DEPTH,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=2,
        max_value=50,
        unit="nodes",
        requires_flag="enable_adaptive_retrieval_depth",
    ),
    # --- Query Pipeline ---
    "multi_query_count": SettingMeta(
        display_name="Multi-Query Variants",
        description="Number of query reformulations generated for multi-query expansion.",
        category=SettingCategory.QUERY,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=2,
        max_value=10,
        requires_flag="enable_multi_query_expansion",
    ),
    "grading_confidence_threshold": SettingMeta(
        display_name="Grading Confidence Threshold",
        description="Median score below which LLM grading is triggered for retrieved chunks.",
        category=SettingCategory.QUERY,
        setting_type=SettingType.FLOAT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=0.0,
        max_value=1.0,
        step=0.05,
        requires_flag="enable_retrieval_grading",
    ),
    "retrieval_grading_keyword_weight": SettingMeta(
        display_name="Grading Keyword Weight",
        description="Keyword overlap weight in heuristic grading blend (0.0-1.0).",
        category=SettingCategory.QUERY,
        setting_type=SettingType.FLOAT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=0.0,
        max_value=1.0,
        step=0.05,
        requires_flag="enable_retrieval_grading",
    ),
    "hyde_blend_ratio": SettingMeta(
        display_name="HyDE Blend Ratio",
        description="Blend factor between query and HyDE vector (0.0 = query only, 1.0 = HyDE only).",
        category=SettingCategory.QUERY,
        setting_type=SettingType.FLOAT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=0.0,
        max_value=1.0,
        step=0.05,
        requires_flag="enable_hyde",
    ),
    "self_reflection_faithfulness_threshold": SettingMeta(
        display_name="Faithfulness Threshold",
        description="Citation faithfulness score below which self-reflection retry triggers.",
        category=SettingCategory.QUERY,
        setting_type=SettingType.FLOAT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=0.0,
        max_value=1.0,
        step=0.05,
        requires_flag="enable_self_reflection",
    ),
    "self_reflection_max_retries": SettingMeta(
        display_name="Max Reflection Retries",
        description="Maximum number of self-reflection retry loops.",
        category=SettingCategory.QUERY,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=0,
        max_value=5,
        requires_flag="enable_self_reflection",
    ),
    "self_reflection_min_claims": SettingMeta(
        display_name="Min Claims for Reflection",
        description="Minimum number of claims before reflection can trigger.",
        category=SettingCategory.QUERY,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=1,
        max_value=20,
        requires_flag="enable_self_reflection",
    ),
    "max_claims_to_verify": SettingMeta(
        display_name="Max Claims to Verify",
        description="Maximum number of claims verified per response by the citation verifier.",
        category=SettingCategory.QUERY,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=1,
        max_value=20,
        unit="claims",
    ),
    "quality_monitoring_sample_rate": SettingMeta(
        display_name="Quality Monitor Sample Rate",
        description="Fraction of production queries sampled for quality scoring.",
        category=SettingCategory.QUERY,
        setting_type=SettingType.FLOAT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=0.0,
        max_value=1.0,
        step=0.05,
        requires_flag="enable_production_quality_monitoring",
    ),
    # --- Agent ---
    "agentic_recursion_limit_fast": SettingMeta(
        display_name="Fast Query Recursion Limit",
        description="Max tool-call iterations for fast (simple) queries.",
        category=SettingCategory.AGENT,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=4,
        max_value=60,
    ),
    "agentic_recursion_limit_standard": SettingMeta(
        display_name="Standard Query Recursion Limit",
        description="Max tool-call iterations for standard queries.",
        category=SettingCategory.AGENT,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=8,
        max_value=80,
    ),
    "agentic_recursion_limit_deep": SettingMeta(
        display_name="Deep Query Recursion Limit",
        description="Max tool-call iterations for deep (complex) queries.",
        category=SettingCategory.AGENT,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=16,
        max_value=120,
    ),
    # --- Ingestion & Processing ---
    "chunk_size": SettingMeta(
        display_name="Chunk Size",
        description="Target size for semantic text chunks during ingestion.",
        category=SettingCategory.INGESTION,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.RESTART,
        min_value=128,
        max_value=2048,
        unit="tokens",
    ),
    "chunk_overlap": SettingMeta(
        display_name="Chunk Overlap",
        description="Overlap between adjacent chunks during ingestion.",
        category=SettingCategory.INGESTION,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.RESTART,
        min_value=0,
        max_value=512,
        unit="tokens",
    ),
    "embedding_batch_size": SettingMeta(
        display_name="Embedding Batch Size",
        description="Number of items per embedding API call.",
        category=SettingCategory.INGESTION,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=1,
        max_value=500,
        unit="items",
    ),
    "contextual_chunk_max_tokens": SettingMeta(
        display_name="Contextual Chunk Max Tokens",
        description="Maximum tokens for contextual chunk prefix generation.",
        category=SettingCategory.INGESTION,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=50,
        max_value=500,
        unit="tokens",
        requires_flag="enable_contextual_chunks",
    ),
    "contextual_chunk_batch_size": SettingMeta(
        display_name="Contextual Chunk Batch Size",
        description="Chunks per LLM call for contextual enrichment.",
        category=SettingCategory.INGESTION,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=1,
        max_value=100,
        requires_flag="enable_contextual_chunks",
    ),
    "contextual_chunk_concurrency": SettingMeta(
        display_name="Contextual Chunk Concurrency",
        description="Concurrent batches for contextual chunk enrichment.",
        category=SettingCategory.INGESTION,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=1,
        max_value=16,
        requires_flag="enable_contextual_chunks",
    ),
    "multi_representation_concurrency": SettingMeta(
        display_name="Multi-Rep Concurrency",
        description="Concurrent batches for multi-representation summary generation.",
        category=SettingCategory.INGESTION,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=1,
        max_value=16,
        requires_flag="enable_multi_representation",
    ),
    "hot_doc_score_threshold": SettingMeta(
        display_name="Hot Doc Score Threshold",
        description="Minimum significance score for a document to be flagged as a hot doc.",
        category=SettingCategory.INGESTION,
        setting_type=SettingType.FLOAT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=0.0,
        max_value=1.0,
        step=0.05,
        requires_flag="enable_hot_doc_detection",
    ),
    "dedup_jaccard_threshold": SettingMeta(
        display_name="Dedup Jaccard Threshold",
        description="MinHash Jaccard similarity threshold for near-duplicate detection.",
        category=SettingCategory.INGESTION,
        setting_type=SettingType.FLOAT,
        risk_level=SettingRiskLevel.CACHE_CLEAR,
        min_value=0.0,
        max_value=1.0,
        step=0.05,
        di_caches=["get_dedup_detector"],
        requires_flag="enable_near_duplicate_detection",
    ),
    "dedup_num_permutations": SettingMeta(
        display_name="Dedup Permutations",
        description="Number of MinHash permutations (higher = more accurate, slower).",
        category=SettingCategory.INGESTION,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.CACHE_CLEAR,
        min_value=32,
        max_value=512,
        di_caches=["get_dedup_detector"],
        requires_flag="enable_near_duplicate_detection",
    ),
    "bertopic_min_cluster_size": SettingMeta(
        display_name="Min Cluster Size",
        description="Minimum documents per topic cluster in BERTopic.",
        category=SettingCategory.INGESTION,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=2,
        max_value=50,
        requires_flag="enable_topic_clustering",
    ),
    # --- Visual Reranking ---
    "visual_rerank_weight": SettingMeta(
        display_name="Visual Rerank Weight",
        description="Blend factor for visual score fusion with text scores.",
        category=SettingCategory.VISUAL,
        setting_type=SettingType.FLOAT,
        risk_level=SettingRiskLevel.CACHE_CLEAR,
        min_value=0.0,
        max_value=1.0,
        step=0.05,
        di_caches=["get_retriever"],
        requires_flag="enable_visual_embeddings",
    ),
    "visual_rerank_top_n": SettingMeta(
        display_name="Visual Rerank Candidates",
        description="Number of candidates visually reranked per query.",
        category=SettingCategory.VISUAL,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.CACHE_CLEAR,
        min_value=1,
        max_value=100,
        di_caches=["get_retriever"],
        requires_flag="enable_visual_embeddings",
    ),
    "visual_page_dpi": SettingMeta(
        display_name="PDF Page DPI",
        description="DPI for rendering PDF pages for visual embedding.",
        category=SettingCategory.VISUAL,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.CACHE_CLEAR,
        min_value=72,
        max_value=300,
        unit="DPI",
        di_caches=["get_visual_embedder"],
        requires_flag="enable_visual_embeddings",
    ),
    # --- Auth & Limits ---
    "rate_limit_queries_per_minute": SettingMeta(
        display_name="Query Rate Limit",
        description="Maximum query API calls per user per minute.",
        category=SettingCategory.AUTH,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=1,
        max_value=1000,
        unit="req/min",
    ),
    "rate_limit_ingests_per_minute": SettingMeta(
        display_name="Ingest Rate Limit",
        description="Maximum ingest API calls per user per minute.",
        category=SettingCategory.AUTH,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=1,
        max_value=100,
        unit="req/min",
    ),
    "audit_retention_days": SettingMeta(
        display_name="Audit Retention",
        description="Number of days to retain audit log entries.",
        category=SettingCategory.AUTH,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=30,
        max_value=3650,
        unit="days",
    ),
    "export_max_documents": SettingMeta(
        display_name="Export Max Documents",
        description="Maximum number of documents per export operation.",
        category=SettingCategory.AUTH,
        setting_type=SettingType.INT,
        risk_level=SettingRiskLevel.SAFE,
        min_value=100,
        max_value=100000,
    ),
}


def validate_registry() -> None:
    """Verify all registry entries map to real Settings attributes.

    Called at import time to catch stale entries early.
    """
    from app.config import Settings

    settings_fields = set(Settings.model_fields.keys())
    for setting_name in SETTING_REGISTRY:
        if setting_name not in settings_fields:
            raise ValueError(f"SETTING_REGISTRY key '{setting_name}' not found in Settings")


validate_registry()
