/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CaseSetupRouteImport } from './routes/case-setup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntitiesIndexRouteImport } from './routes/entities/index'
import { Route as DocumentsIndexRouteImport } from './routes/documents/index'
import { Route as DatasetsIndexRouteImport } from './routes/datasets/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ReviewResultSetRouteImport } from './routes/review/result-set'
import { Route as ReviewHotDocsRouteImport } from './routes/review/hot-docs'
import { Route as ReviewExportsRouteImport } from './routes/review/exports'
import { Route as EntitiesNetworkRouteImport } from './routes/entities/network'
import { Route as EntitiesIdRouteImport } from './routes/entities/$id'
import { Route as DocumentsImportRouteImport } from './routes/documents/import'
import { Route as DocumentsCompareRouteImport } from './routes/documents/compare'
import { Route as DocumentsIdRouteImport } from './routes/documents/$id'
import { Route as ChatThreadIdRouteImport } from './routes/chat/$threadId'
import { Route as AnalyticsTimelineRouteImport } from './routes/analytics/timeline'
import { Route as AnalyticsCommsRouteImport } from './routes/analytics/comms'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminOperationsRouteImport } from './routes/admin/operations'
import { Route as AdminLlmSettingsRouteImport } from './routes/admin/llm-settings'
import { Route as AdminKnowledgeGraphRouteImport } from './routes/admin/knowledge-graph'
import { Route as AdminFeatureFlagsRouteImport } from './routes/admin/feature-flags'
import { Route as AdminEvaluationRouteImport } from './routes/admin/evaluation'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AuthOidcCallbackRouteImport } from './routes/auth/oidc/callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseSetupRoute = CaseSetupRouteImport.update({
  id: '/case-setup',
  path: '/case-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesIndexRoute = EntitiesIndexRouteImport.update({
  id: '/entities/',
  path: '/entities/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewResultSetRoute = ReviewResultSetRouteImport.update({
  id: '/review/result-set',
  path: '/review/result-set',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewHotDocsRoute = ReviewHotDocsRouteImport.update({
  id: '/review/hot-docs',
  path: '/review/hot-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewExportsRoute = ReviewExportsRouteImport.update({
  id: '/review/exports',
  path: '/review/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesNetworkRoute = EntitiesNetworkRouteImport.update({
  id: '/entities/network',
  path: '/entities/network',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/entities/network.lazy').then((d) => d.Route),
)
const EntitiesIdRoute = EntitiesIdRouteImport.update({
  id: '/entities/$id',
  path: '/entities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsImportRoute = DocumentsImportRouteImport.update({
  id: '/documents/import',
  path: '/documents/import',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/documents/import.lazy').then((d) => d.Route),
)
const DocumentsCompareRoute = DocumentsCompareRouteImport.update({
  id: '/documents/compare',
  path: '/documents/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/documents/$id.lazy').then((d) => d.Route))
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/chat/$threadId.lazy').then((d) => d.Route),
)
const AnalyticsTimelineRoute = AnalyticsTimelineRouteImport.update({
  id: '/analytics/timeline',
  path: '/analytics/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsCommsRoute = AnalyticsCommsRouteImport.update({
  id: '/analytics/comms',
  path: '/analytics/comms',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/analytics/comms.lazy').then((d) => d.Route),
)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/admin/operations',
  path: '/admin/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLlmSettingsRoute = AdminLlmSettingsRouteImport.update({
  id: '/admin/llm-settings',
  path: '/admin/llm-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKnowledgeGraphRoute = AdminKnowledgeGraphRouteImport.update({
  id: '/admin/knowledge-graph',
  path: '/admin/knowledge-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeatureFlagsRoute = AdminFeatureFlagsRouteImport.update({
  id: '/admin/feature-flags',
  path: '/admin/feature-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEvaluationRoute = AdminEvaluationRouteImport.update({
  id: '/admin/evaluation',
  path: '/admin/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/admin/audit-log',
  path: '/admin/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOidcCallbackRoute = AuthOidcCallbackRouteImport.update({
  id: '/auth/oidc/callback',
  path: '/auth/oidc/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-setup': typeof CaseSetupRoute
  '/login': typeof LoginRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/knowledge-graph': typeof AdminKnowledgeGraphRoute
  '/admin/llm-settings': typeof AdminLlmSettingsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/comms': typeof AnalyticsCommsRoute
  '/analytics/timeline': typeof AnalyticsTimelineRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/compare': typeof DocumentsCompareRoute
  '/documents/import': typeof DocumentsImportRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/entities/network': typeof EntitiesNetworkRoute
  '/review/exports': typeof ReviewExportsRoute
  '/review/hot-docs': typeof ReviewHotDocsRoute
  '/review/result-set': typeof ReviewResultSetRoute
  '/chat/': typeof ChatIndexRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/entities/': typeof EntitiesIndexRoute
  '/auth/oidc/callback': typeof AuthOidcCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-setup': typeof CaseSetupRoute
  '/login': typeof LoginRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/knowledge-graph': typeof AdminKnowledgeGraphRoute
  '/admin/llm-settings': typeof AdminLlmSettingsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/comms': typeof AnalyticsCommsRoute
  '/analytics/timeline': typeof AnalyticsTimelineRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/compare': typeof DocumentsCompareRoute
  '/documents/import': typeof DocumentsImportRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/entities/network': typeof EntitiesNetworkRoute
  '/review/exports': typeof ReviewExportsRoute
  '/review/hot-docs': typeof ReviewHotDocsRoute
  '/review/result-set': typeof ReviewResultSetRoute
  '/chat': typeof ChatIndexRoute
  '/datasets': typeof DatasetsIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/entities': typeof EntitiesIndexRoute
  '/auth/oidc/callback': typeof AuthOidcCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-setup': typeof CaseSetupRoute
  '/login': typeof LoginRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/knowledge-graph': typeof AdminKnowledgeGraphRoute
  '/admin/llm-settings': typeof AdminLlmSettingsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/comms': typeof AnalyticsCommsRoute
  '/analytics/timeline': typeof AnalyticsTimelineRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/compare': typeof DocumentsCompareRoute
  '/documents/import': typeof DocumentsImportRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/entities/network': typeof EntitiesNetworkRoute
  '/review/exports': typeof ReviewExportsRoute
  '/review/hot-docs': typeof ReviewHotDocsRoute
  '/review/result-set': typeof ReviewResultSetRoute
  '/chat/': typeof ChatIndexRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/entities/': typeof EntitiesIndexRoute
  '/auth/oidc/callback': typeof AuthOidcCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case-setup'
    | '/login'
    | '/admin/audit-log'
    | '/admin/evaluation'
    | '/admin/feature-flags'
    | '/admin/knowledge-graph'
    | '/admin/llm-settings'
    | '/admin/operations'
    | '/admin/users'
    | '/analytics/comms'
    | '/analytics/timeline'
    | '/chat/$threadId'
    | '/documents/$id'
    | '/documents/compare'
    | '/documents/import'
    | '/entities/$id'
    | '/entities/network'
    | '/review/exports'
    | '/review/hot-docs'
    | '/review/result-set'
    | '/chat/'
    | '/datasets/'
    | '/documents/'
    | '/entities/'
    | '/auth/oidc/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/case-setup'
    | '/login'
    | '/admin/audit-log'
    | '/admin/evaluation'
    | '/admin/feature-flags'
    | '/admin/knowledge-graph'
    | '/admin/llm-settings'
    | '/admin/operations'
    | '/admin/users'
    | '/analytics/comms'
    | '/analytics/timeline'
    | '/chat/$threadId'
    | '/documents/$id'
    | '/documents/compare'
    | '/documents/import'
    | '/entities/$id'
    | '/entities/network'
    | '/review/exports'
    | '/review/hot-docs'
    | '/review/result-set'
    | '/chat'
    | '/datasets'
    | '/documents'
    | '/entities'
    | '/auth/oidc/callback'
  id:
    | '__root__'
    | '/'
    | '/case-setup'
    | '/login'
    | '/admin/audit-log'
    | '/admin/evaluation'
    | '/admin/feature-flags'
    | '/admin/knowledge-graph'
    | '/admin/llm-settings'
    | '/admin/operations'
    | '/admin/users'
    | '/analytics/comms'
    | '/analytics/timeline'
    | '/chat/$threadId'
    | '/documents/$id'
    | '/documents/compare'
    | '/documents/import'
    | '/entities/$id'
    | '/entities/network'
    | '/review/exports'
    | '/review/hot-docs'
    | '/review/result-set'
    | '/chat/'
    | '/datasets/'
    | '/documents/'
    | '/entities/'
    | '/auth/oidc/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseSetupRoute: typeof CaseSetupRoute
  LoginRoute: typeof LoginRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminEvaluationRoute: typeof AdminEvaluationRoute
  AdminFeatureFlagsRoute: typeof AdminFeatureFlagsRoute
  AdminKnowledgeGraphRoute: typeof AdminKnowledgeGraphRoute
  AdminLlmSettingsRoute: typeof AdminLlmSettingsRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AnalyticsCommsRoute: typeof AnalyticsCommsRoute
  AnalyticsTimelineRoute: typeof AnalyticsTimelineRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  DocumentsIdRoute: typeof DocumentsIdRoute
  DocumentsCompareRoute: typeof DocumentsCompareRoute
  DocumentsImportRoute: typeof DocumentsImportRoute
  EntitiesIdRoute: typeof EntitiesIdRoute
  EntitiesNetworkRoute: typeof EntitiesNetworkRoute
  ReviewExportsRoute: typeof ReviewExportsRoute
  ReviewHotDocsRoute: typeof ReviewHotDocsRoute
  ReviewResultSetRoute: typeof ReviewResultSetRoute
  ChatIndexRoute: typeof ChatIndexRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  EntitiesIndexRoute: typeof EntitiesIndexRoute
  AuthOidcCallbackRoute: typeof AuthOidcCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-setup': {
      id: '/case-setup'
      path: '/case-setup'
      fullPath: '/case-setup'
      preLoaderRoute: typeof CaseSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/': {
      id: '/entities/'
      path: '/entities'
      fullPath: '/entities/'
      preLoaderRoute: typeof EntitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/result-set': {
      id: '/review/result-set'
      path: '/review/result-set'
      fullPath: '/review/result-set'
      preLoaderRoute: typeof ReviewResultSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/hot-docs': {
      id: '/review/hot-docs'
      path: '/review/hot-docs'
      fullPath: '/review/hot-docs'
      preLoaderRoute: typeof ReviewHotDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/exports': {
      id: '/review/exports'
      path: '/review/exports'
      fullPath: '/review/exports'
      preLoaderRoute: typeof ReviewExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/network': {
      id: '/entities/network'
      path: '/entities/network'
      fullPath: '/entities/network'
      preLoaderRoute: typeof EntitiesNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$id': {
      id: '/entities/$id'
      path: '/entities/$id'
      fullPath: '/entities/$id'
      preLoaderRoute: typeof EntitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/import': {
      id: '/documents/import'
      path: '/documents/import'
      fullPath: '/documents/import'
      preLoaderRoute: typeof DocumentsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/compare': {
      id: '/documents/compare'
      path: '/documents/compare'
      fullPath: '/documents/compare'
      preLoaderRoute: typeof DocumentsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/timeline': {
      id: '/analytics/timeline'
      path: '/analytics/timeline'
      fullPath: '/analytics/timeline'
      preLoaderRoute: typeof AnalyticsTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/comms': {
      id: '/analytics/comms'
      path: '/analytics/comms'
      fullPath: '/analytics/comms'
      preLoaderRoute: typeof AnalyticsCommsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/llm-settings': {
      id: '/admin/llm-settings'
      path: '/admin/llm-settings'
      fullPath: '/admin/llm-settings'
      preLoaderRoute: typeof AdminLlmSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/knowledge-graph': {
      id: '/admin/knowledge-graph'
      path: '/admin/knowledge-graph'
      fullPath: '/admin/knowledge-graph'
      preLoaderRoute: typeof AdminKnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feature-flags': {
      id: '/admin/feature-flags'
      path: '/admin/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AdminFeatureFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evaluation': {
      id: '/admin/evaluation'
      path: '/admin/evaluation'
      fullPath: '/admin/evaluation'
      preLoaderRoute: typeof AdminEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/oidc/callback': {
      id: '/auth/oidc/callback'
      path: '/auth/oidc/callback'
      fullPath: '/auth/oidc/callback'
      preLoaderRoute: typeof AuthOidcCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseSetupRoute: CaseSetupRoute,
  LoginRoute: LoginRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminEvaluationRoute: AdminEvaluationRoute,
  AdminFeatureFlagsRoute: AdminFeatureFlagsRoute,
  AdminKnowledgeGraphRoute: AdminKnowledgeGraphRoute,
  AdminLlmSettingsRoute: AdminLlmSettingsRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AnalyticsCommsRoute: AnalyticsCommsRoute,
  AnalyticsTimelineRoute: AnalyticsTimelineRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
  DocumentsIdRoute: DocumentsIdRoute,
  DocumentsCompareRoute: DocumentsCompareRoute,
  DocumentsImportRoute: DocumentsImportRoute,
  EntitiesIdRoute: EntitiesIdRoute,
  EntitiesNetworkRoute: EntitiesNetworkRoute,
  ReviewExportsRoute: ReviewExportsRoute,
  ReviewHotDocsRoute: ReviewHotDocsRoute,
  ReviewResultSetRoute: ReviewResultSetRoute,
  ChatIndexRoute: ChatIndexRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  EntitiesIndexRoute: EntitiesIndexRoute,
  AuthOidcCallbackRoute: AuthOidcCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
